### ISSUE TITLE
Appendix where?

### ISSUE THREAD

**Issue by kanishkanarch** [StanfordVL/behavioral_navigation_nlp#1]
Thank you for this wonderful work. There are multiple references to the Appendix or Appendix A inside your paper, but it is nowhere to be found. Kindly guide me where can I find the supplementary material for the research work.

**Comment by kanishkanarch** [comment]
Also, in the `predictions.txt` file of the pretrained model on the given dataset, the second row seems a bit off to me (see the image below). Second of the last three numbers denote the number of behaviour attributes, which should be `2` in the 2nd line, instead of `7`.
**Also, please explain the meaning of other two of the three appended numbers**

![image](https://user-images.githubusercontent.com/52484751/172647804-5c52de78-047d-4611-8661-b2a5da7cb6fd.png)

**Comment by ashwinipokle** [comment]
Thanks for your interest in this work. I have attached the pdf of Appendix here. 
[Translating_Navigation_Instructions_in_Natural_Language___to_a_High_Level_Plan_for_Behavioral_Robot_Navigation________Supplementary_Appendix___.pdf](https://github.com/StanfordVL/behavioral_navigation_nlp/files/8932813/Translating_Navigation_Instructions_in_Natural_Language___to_a_High_Level_Plan_for_Behavioral_Robot_Navigation________Supplementary_Appendix___.pdf)
 
The second last number in each row indicates the number of tokens in the ground truth prediction. Therefore, as you pointed out, the prediction in the second row is incorrect as it is shorter.

The last number in each row is the Exact Match (EM) score (1 for correct and 0 for incorrect prediction)

This line from the codebase might be useful https://github.com/StanfordVL/behavioral_navigation_nlp/blob/981300f58c468f902c5fb2953be7eb4bff2376c5/codes/qa_model.py#L505

**Comment by kanishkanarch** [comment]
Thank you very much, Ashwini.
I didn't know that you are also a BITSian 😃 
Really inspiring work on machine translation!!!
